LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_SRC_FILES := pvrsrvinit.c
LOCAL_LDFLAGS := -L $(TARGET_OUT_VENDOR_SHARED_LIBRARIES)
LOCAL_ADDITIONAL_DEPENDENCIES := $(TARGET_OUT_VENDOR)/lib/libsrv_init_SGX540_120.so $(TARGET_OUT_VENDOR)/lib/libsrv_um_SGX540_120.so
LOCAL_LDFLAGS += -lsrv_init_SGX540_120 -lsrv_um_SGX540_120
LOCAL_MODULE_PATH := $(TARGET_OUT_EXECUTABLES)
LOCAL_MODULE := pvrsrvinit
LOCAL_MODULE_TAGS := optional

include $(BUILD_EXECUTABLE)

